### ISSUE TITLE
加上下拉刷新，频繁更新数据集会崩溃

### ISSUE THREAD

**Issue by zhierfeifei** [Othershe/RecyclerViewAdapter#16]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{9ef0e74 position=9 id=-1, oldPos=-1, pLpos:-1 no parent} android.support.v7.widget.RecyclerView{22c9fd9 VFED..... .F...... 0,0-1440,1974 #7f09025c app:id/recyclerView}, adapter:com.fuju.yuefang.ui.mine.attention.PersonRefreshAdapter@8a5d9e, layout:com.fuju.yuefang.ui.mine.attention.AttentionPersonFragment$2@9a4307f, context:com.fuju.yuefang.ui.mine.attention.AttentionActivity@902b432
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5610)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5792)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by shehuan** [comment]
可以尝试参考demo里的WrapLinearLayoutManager，重写LayoutManager

**Comment by zhierfeifei** [comment]
reset方法里，data清空后，没有及时更新，所以导致数据集不一致，然后会崩溃
    /**
     * 重置adapter，恢复到初始状态
     */
    public void reset() {
        if (mLoadingView != null) {
            addFooterView(mLoadingView);
        }
        isLoading = false;
        isReset = true;
        isAutoLoadMoreEnd = false;
        mDatas.clear();
        notifyDataSetChanged(); //加上这一句
    }
